import json,hashlib,math,subprocess
from pathlib import Path
from build_clips import specs,src,out,ev
# build_clips repeats deterministic encoding/decoding before manifest creation.
clock=json.loads((ev/'capture-clock-evidence.json').read_text())
meta=[('Rock Drake trench black pearl clusters',['Black Pearls'],67.6,52,'Black pearl clusters clearly filmed on purple ground; dedicated Black Pearls chapter narration source665–674s identifies trench/element-river clusters.'),('Dense Blue Zone crystal and gem field',['Crystal'],48.7,78.6,'Dense blue gem/crystal nodes clearly filmed. Primary official community wiki confirms Aberration colored gem patches yield Crystal: https://ark.wiki.gg/wiki/Crystals. No measured yield claimed.'),('Accessible red gem crystal field',['Crystal'],45,36.7,'Purple crystalline nodes visibly filmed in creator-labelled accessible red gem field. Primary official community wiki confirms Aberration colored gem patches yield Crystal: https://ark.wiki.gg/wiki/Crystals.'),('Blue and red border polymer plants',['Organic Polymer'],61.7,72.9,'Distinct spotted organic polymer plants clearly filmed in Organic Polymer chapter. Narration source947–963s identifies plant harvesting; no inventory/yield proof.'),('River redwood honey hive',['Giant Bee Honey'],44.1,31,'Hive visibly attached to redwood tree approached continuously. Creator Giant Bee Honey chapter identifies this as one of two found hives; spawn is conditional, not guaranteed.'),('Portal-side redwood honey hive',['Giant Bee Honey'],38.2,39,'Second hive visibly attached to redwood tree in separate continuously filmed site. Creator identifies two hives; spawn is conditional, not guaranteed.')]
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
c=[]
for (id,t,d,gps),(name,resources,lat,lon,proof) in zip(specs,meta):
 clip=out/f'{id}.mp4';poster=out/f'{id}.jpg';duration=float(subprocess.check_output(['ffprobe','-v','error','-show_entries','format=duration','-of','csv=p=0',str(clip)]))
 n=math.ceil(duration*4)
 c.append(dict(id=id,map='aberration',name=name,resources=resources,lat=lat,lon=lon,videoID='TUoB8ouWPYk',startSeconds=math.floor(t),endSeconds=math.ceil(t+d),coordinateEvidence=f'Creator numerical label {lat:g} LAT / {lon:g} LONG at source{gps}s; explicit large typed creator LAT/LONG regional label. Full uncropped frame retained. Native map-bottom readout authority is unverified and not relied on.',inventoryEvidence=proof,clipPath=str(clip),posterPath=str(poster),sourceURL='https://www.youtube.com/watch?v=TUoB8ouWPYk',sourcePlane='Aberration ASA coordinate plane',sourceCoordinateScope='Creator-labelled filmed farming region; not actual native player GPS',mapOverlayVisible=False,creatorInsetVisible=False,inventoryOverlayVisible=False,rightsBasis='licensed',acquisitionState='User-authorized licensed public Chrome playback captured in isolated native window; no denied download or authentication bypass',sourcePath=str(src),sourceSHA256=clock['sourceSHA256'],clipSHA256=sha(clip),posterSHA256=sha(poster),visualReview={'contactSheet':str(ev/f'{id}-contact.jpg'),'coordinateFrame':str(ev/f'{id}-coordinate.jpg'),'fullEncodedDecode':True,'sampleRateFPS':4,'continuousShot':True,'reviewed':True,'result':f'All {n} chronological 4fps samples manually reviewed: continuous clean resource/terrain shot; no M-map, inventory, creator inset, captions or shot cuts. Full encoded file decoded without errors.'},evidenceLimitations='Filmed 2024 ASA source, region waypoint rather than every exact node; no permanent spawn/node count or guaranteed yield. '+('Clean shot is shorter than8 seconds because nearby hard cuts/map overlays were excluded. ' if d<8 else '')+('Hive only, no queen/harvest inventory shown; creator discusses difficulty and empty hives.' if 'Honey' in resources[0] else ''),visualReviewStatus='verified',sourceCrop={'x':0,'y':0,'width':1184,'height':666,'sourceWidth':1184,'sourceHeight':666,'reason':'No spatial crop; clean source segment selected.'},captureCut={'sourceStartSeconds':t,'sourceDurationSeconds':d,'captureStartSeconds':12.251+(t-.068941)/2,'captureDurationSeconds':d/2,'encodedDurationSeconds':duration,'naturalSpeedRestorationFactor':2},sourcePublishedDate='2024-09-10',sourceTitle='The Ultimate Aberration Resource Guide, 50+ Tips/Locations, Ark Survival Ascended',sourceCreator='Chaos Bear Gaming'))
rejects=[{'resource':'Rare Flowers / Rare Mushrooms','sourceRange':[720,817],'reason':'Clear Blue Zone mushroom footage but no numerical GPS for these sites; descriptive whole-biome map overlay cannot invent waypoint.'},{'resource':'Oil','sourceRange':[1001,1068],'reason':'Clear oil nodes/creature methods but no numerical GPS to establish additional site.'},{'resource':'Cementing Paste','sourceRange':[820,911],'reason':'Generic frog/Achatina/crafting method footage; no numerical GPS; repeated methods are not distinct farm sites.'},{'resource':'Chitin','sourceRange':[912,946],'reason':'Creature/bone method shots have no numerical GPS in this half. Keratin bone source is not Chitin.'},{'resource':'Crystal, green Portal patches','sourceRange':[530,562],'reason':'Crystal yield is explicitly narrated541–560s, but numerical GPS lies outside second-half assignment; parent may establish it from first half.'}]
for item in c:
 item['sourceCapture']=clock
 item['sourceTimestampURL']=item['sourceURL']+'&t='+str(item['startSeconds'])+'s'
held=[item for item in c if item['captureCut']['encodedDurationSeconds']<6]
for item in held:
 item['integrationState']='hold';item['holdReason']='Clean source shot under6 seconds; preserve location/GPS proof pending longer legitimate source shot'
c=[item for item in c if item not in held]
(ev/'reviewed-additions.json').write_text(json.dumps({'candidates':c,'heldCandidates':held,'reviewedSourceRangeSeconds':[530,1319],'captureClockEvidence':str(ev/'capture-clock-evidence.json'),'duplicateAudit':{'nativeManifest':'native/Ascended/Resources/verified-resource-spots.json','existingAberrationIDs':['aberration-green-metal','aberration-blue-metal','aberration-blue-polymer-488-509','aberration-tek-pond-pearls-628-507'],'result':'All6 candidate waypoints materially distinct from existing same-resource accepted waypoints; no second angle counted.'},'rejectedUnlocatedMethods':rejects,'reviewerNote':'Four verified6–10sec deliverables and two shorter held sites. Root confirms licensed authorized public native Chrome playback capture rights.'},indent=2))
print('6 candidates written, all files exist and hashes retained')
