import pathlib,json,shutil,collections
root=pathlib.Path('/Users/admin/Ascended-iPad-Dev');p=root/'tools/evidence/farming32/story';external=pathlib.Path('/Volumes/TONY SSD/ASCENDED_MEDIA/farming32/story');maps=['scorched-earth','aberration','extinction','lost-colony'];resources=['Black Pearls','Cementing Paste','Chitin','Crystal','Giant Bee Honey','Metal','Obsidian','Oil','Organic Polymer','Rare Flowers','Rare Mushrooms','Rich Metal','Sap','Silica Pearls']
cat=json.loads((root/'native/Ascended/Resources/verified-resource-spots.json').read_text());selections=json.loads((root/'tools/resource_clip_selections.json').read_text());add=json.loads((p/'additions.json').read_text())['entries'];existing=[]
for s in cat['spots']:
 if s['map'] not in maps:continue
 sel=selections[s['id']];existing.append(dict(s,startSeconds=sel['startSeconds'],endSeconds=sel['startSeconds']+sel['duration'],clipPath=str(root/'native/Ascended/Resources/ResourceClips'/('Resource-'+s['id']+'-1.mp4')),status='existing-verified',license='User-asserted licensed; metadata license null',visualReview=sel['visualReview']))
for a in add:
 a['visualReview']={'method':'Manual encoded contact sheet inspection at 8 fps after boundary repairs; fully decoded with ffmpeg -xerror','result':'Clean continuous terrain/approach with no M map or inventory/menu obstruction; normal gameplay HUD and creator coordinate text may remain','reviewedAt':'2026-10-08','samplingLimit':'8 fps samples, not every frame'};a['status']='new-candidate-verified-camera-region';a['inventoryEvidence']='No completed harvest demonstrated. Visible resource/approach belongs to source resource segment.';a['direction']='Use coordinates as the filmed region, then match the visible terrain and approach.';a['method']='Use an appropriate harvesting tool or tame for this resource; resource yield is not measured by this preview.';a['kit']=[];a['risks']=['Hostile creatures','Terrain hazards'];a['sourcePlane']=a['map']+' filmed region';a['sourceCoordinateScope']='Filmed camera/waypoint region; not every actor or permanent spawn.'
 if a['map']=='lost-colony':a['limitations']='Pin uses camera/map coordinates visible at69s (3.0/5.8), not an edited exact metal waypoint. Video shows the same northwestern snowy metal area continuously; camera moves during map zoom.'
 if a['id']=='scorched-northeast-cliff-metal':a['limitations']='Only1s clean view of third metal cliff approach; intact partial ends during subsequent map; ore harvest not visible. User specified maximum10s, no minimum, but parent may reject as too short for useful instruction.'
 if a['id']=='aberration-northwest-metal-cave':a['limitations']='Clip establishes green-zone cave entrance approach within Metal guide; no completed ore harvest demonstrated.'
 if a['map']=='extinction':a['limitations']='Very short clean pool terrain view; source coordinates are explicit camera and creator overlays. No harvest demonstrated.'
(p/'additions.json').write_text(json.dumps({'entries':add},indent=2))
allrows=existing+add;coverage=[]
alias={'Giant Bee Honey':['Bee Hive'],'Cementing Paste':['Beaver Dam'],'Organic Polymer':['Organic Polymer','Polymer'],'Rare Mushrooms':['Rare Mushrooms'],'Sap':['Sap']}
for map in maps:
 raw=json.loads((root/'native/Ascended/Resources'/(map+'-resources.json')).read_text());counts=collections.Counter(x['resource_type'] for x in raw)
 for res in resources:
  prev=next((c for c in cat['coverage'] if c['map']==map and c['resource']==res),None);spots=[a['id'] for a in allrows if a['map']==map and res in a['resources']]
  coverage.append(dict(map=map,resource=res,existingStatus=prev['status'] if prev else 'not-in-existing-coverage',existingReason=prev.get('reason') if prev else None,verifiedCandidateCount=len(spots),spotIDs=spots,meetsThreeLocations=len(spots)>=3,rawLayerCount=sum(counts[x] for x in alias.get(res,[res])),gap=max(0,3-len(spots)),status='candidate-target-met' if len(spots)>=3 else 'incomplete-source-evidence',note='Raw data count is context only; missing raw layer is not proof resource cannot be acquired. Existing absent/crafting/unverified status is preserved; no arbitrary locations were generated.'))
watch=[]
for vid,map in [('k9IOWvnWMdg','scorched-earth'),('85xkdr_UYAo','extinction'),('WKNYEAeuSDA','lost-colony'),('TUoB8ouWPYk','aberration'),('KIWzuHPxWaE','aberration')]:
 f=external/(vid+'-inspect.json');d=json.loads(f.read_text());watch.append(dict(videoID=vid,map=map,title=d['title'],channel=d['channel'],description=d['description'],chapters=d['chapters'],license=d['license'],status='metadata-only-beyond-intact-cached-ranges',coordinates=None))
 errors=[{'action':'CC filtered compilation search','map':m,'status':'failed','error':'YouTube Data API rejected the request parameters or API key'} for m in maps]
errors+=[{'action':'licensed triple-gated section acquisition','videoID':vid,'status':'failed','error':(external/(vid+'-section.err')).read_text().strip()} for vid in ['k9IOWvnWMdg','85xkdr_UYAo','WKNYEAeuSDA','TUoB8ouWPYk']]
ledger={'schemaVersion':1,'reviewedAt':'2026-10-08','scope':maps,'curatedResources':resources,'existingCount':len(existing),'newCandidateCount':len(add),'newSuccessfulDownloads':0,'newRenderedClipsFromAuthorizedCache':len(add),'entries':allrows,'coverage':coverage,'watchlist':watch,'blockers':errors,'rightsBasis':'Root recovered direct prior user statement Duyệt, a có giấy phép hết. Source metadata license null does not prove CC; all footage uses user-asserted licensed basis. No restriction bypass performed.'}
(p/'candidate-ledger.json').write_text(json.dumps(ledger,indent=2));shutil.copy2(p/'candidate-ledger.json',external/'candidate-ledger.json')
report='Story map research: 6 existing + 5 new rendered candidates. 3 of 56 resource/map pairs reach >=3 candidate locations: Scorched Metal, Aberration Metal, Extinction Oil. Lost Colony Metal has2. All other pairs incomplete. No raw actor coordinates substituted for source-backed clips. New clips are1.0,4.875,6.25,2.417,1.125 seconds; all decoded successfully. Source metadata verified ASA map in title/author description. Four authorised section acquisitions failed with ffmpeg exit8; four CC searches failed API parameter/key error. Preserve per-pair existing acquisition/absence statuses in ledger. Parent must decide whether1s and1.125s previews are useful enough to integrate.\n'
(p/'README.md').write_text(report);print(report)
