"""Export only manually accepted camera-GPS backed source intervals. Never edits live catalogs."""
import json,pathlib,subprocess,hashlib,shutil
ROOT=pathlib.Path(__file__).resolve().parents[3]; E=ROOT/'tools/evidence/farming26-sources'; R=ROOT/'native/Ascended/Resources/ResourceClips'; A=ROOT/'native/Ascended/Assets.xcassets'
paths=json.load(open('/Volumes/TONY SSD/ASCENDED_MEDIA/resource-clip-review/paths.json'))
rows=[
('center-waterfall-cavern','the-center','Southern waterfall cavern',88.8,63.2,['Metal','Crystal'],'bAqRvM-080g',120,132,138,'bAqRvM-080g-120.jpg','Camera GPS at the waterfall approach; nearby cavern is reached continuously from this position.','Metal and Crystal chapter114–187s; white crystal clusters and ore rocks visible inside the cavern.','Follow the waterfall passage into the cavern and examine the rock ledges.','Metal Pick; bring a mount for transport.',['Metal Pick','Argentavis'],['Dark cave','Fall','Predators']),
('center-north-pond-west','the-center','Northern western beaver pond',30.9,52.5,['Beaver Dam','Cementing Paste'],'bAqRvM-080g',348,356,364,'bAqRvM-080g-348.jpg','Camera GPS above the pond approach.','Cementing Paste chapter345–534s; creator follows this pond and its dams. Individual loot is not measured.','Descend into the small waterfall pond and inspect its banks for dams.','Inspect Beaver Dam inventories; clear unwanted contents after collecting.',['Flying mount'],['Angry beavers','Variable dam spawns']),
('center-north-pond-east','the-center','Northern eastern beaver pond',31.1,57.6,['Beaver Dam','Cementing Paste','Silica Pearls','Rare Flowers','Wood'],'bAqRvM-080g',408,414,422,'bAqRvM-080g-408.jpg','Camera GPS above this distinct pond.','Beaver Dam inventory opened at428s; Cementing Paste, Silica Pearls, Rare Flower and Wood are shown. No transfer or yield measurement is claimed.','Follow the water into the pond, then inspect the dam on the bank.','Inspect Beaver Dam inventories; clear unwanted contents after collecting.',['Flying mount'],['Angry beavers','Variable dam spawns']),
('center-middle-pond','the-center','Central jungle beaver pond',42.5,60.3,['Beaver Dam','Cementing Paste'],'bAqRvM-080g',435,441,449,'bAqRvM-080g-435.jpg','Camera GPS above the jungle pond.','Cementing Paste chapter345–534s; filmed pond approach and dam habitat. No specific loot yield is measured.','Descend between the rock walls to the shallow pond and check the banks.','Inspect Beaver Dam inventories; clear unwanted contents after collecting.',['Flying mount'],['Angry beavers','Variable dam spawns']),
('center-south-east-pond','the-center','Southern eastern beaver pond',51.7,60.8,['Beaver Dam','Cementing Paste'],'bAqRvM-080g',471,478,486,'center-pond4-gps471.jpg','Camera GPS above the southern eastern pond.','Cementing Paste chapter345–534s; shallow pond, beaver and dam habitat shown. No specific loot yield is measured.','Descend into the shallow pond and search along the shoreline.','Inspect Beaver Dam inventories; clear unwanted contents after collecting.',['Flying mount'],['Angry beavers','Variable dam spawns']),
('center-south-west-pond','the-center','Southern western beaver pond',53.1,51.0,['Beaver Dam','Cementing Paste','Silica Pearls','Rare Flowers','Wood'],'bAqRvM-080g',505,510,518,'center-gps505.jpg','Camera GPS longitude is displayed as51 without fractional digits, not a guessed decimal.','Beaver Dam inventory at519s shows312 Cementing Paste,12 Silica Pearls,20 Rare Flower and700 Wood in this source sample. These are not guaranteed yields.','Descend into the narrow pond and inspect the dam beside the shoreline.','Inspect Beaver Dam inventories; clear unwanted contents after collecting.',['Flying mount'],['Angry beavers','Variable dam spawns']),
('valguero-west-pearl-bed','valguero','Western lake second pearl bed',44.4,30.4,['Silica Pearls'],'boGcZ2neH6g',73,64.5,70.5,'boGcZ2neH6g-73.jpg','Camera GPS is shown underwater at this second pearl bed.','Silica Pearls opening chapter; glowing pearl shells are shown on the lake floor. Harvest yield is not measured.','Swim to the lake floor and look around the glowing pearl shells.','Collect pearls from the visible shells.',['SCUBA'],['Drowning','Aquatic predators']),
('rag-south-seabed-oil','ragnarok','Southern seabed oil field',90.2,72.1,['Oil'],'0i0-XEV85m8',681,670,678,'rag-oil-gps681.jpg','Actual camera GPS90.2/72.1 is used; the earlier creator caption79/71.1 is a different region and is not copied.','Oil chapter579–711s; oil rocks on the seabed shown directly before the GPS view. No harvest yield is measured.','Dive to the southern seabed and examine the scattered oil rocks.','Mine the oil rocks with a suitable tool.',['SCUBA','Metal Pick'],['Drowning','Aquatic predators']),
('island-cave-black-pearls','the-island','Eastern cave black pearl chamber',45.1,76.3,['Black Pearls'],'IOCye6IYUCM',140,320,328,'IOCye6IYUCM-140.jpg','GPS is recorded inside the filmed cave at140s; the creator revisits its black pearl chamber in316–346s. This is an interior camera coordinate, not an independently verified entrance.','Black Pearls chapter272–370s; glowing black pearl clusters and collection indicator shown in the chamber around326s.','Use the source walkthrough to find the cave; explore the chamber with glowing pearl clusters.','Collect the black pearl clusters shown in the cave.',['SCUBA'],['Cave predators','Drowning','Interior GPS does not identify the entrance'])
]
spots=[];guides=[]
for id,map,name,lat,lon,res,vid,gps,start,end,ev,scope,inv,direction,method,kit,risks in rows:
 base='farm26-new-'+id; clip=R/(base+'.mp4'); poster=R/(base+'.jpg'); asset='Farm26-'+id; aset=A/(asset+'.imageset');aset.mkdir(parents=True,exist_ok=True)
 subprocess.run(['ffmpeg','-v','error','-y','-ss',str(start),'-i',paths[vid],'-t',str(end-start),'-an','-vf','scale=w=min(1920\\,iw):h=-2,fps=24','-c:v','libx264','-crf','20','-preset','fast','-pix_fmt','yuv420p','-movflags','+faststart',str(clip)],check=True)
 subprocess.run(['ffmpeg','-v','error','-y','-ss','1','-i',str(clip),'-frames:v','1',str(poster)],check=True);shutil.copy2(poster,aset/'photo.jpg');(aset/'Contents.json').write_text(json.dumps({'images':[{'filename':'photo.jpg','idiom':'universal'}],'info':{'author':'xcode','version':1}},indent=2)+'\n')
 sheet=E/(id+'-review4fps.jpg');subprocess.run(['ffmpeg','-v','error','-y','-i',str(clip),'-vf','fps=4,scale=320:-1,tile=4x8','-frames:v','1',str(sheet)],check=True)
 sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
 url='https://www.youtube.com/watch?v='+vid; coord=f'In-game camera GPS visible at {gps}s: latitude {lat}, longitude {lon}. {scope} Evidence frame: tools/evidence/farming26-sources/{ev}'
 common={'map':map,'videoID':vid,'sourceURL':url,'sourcePlane':map+' filmed region','sourceCoordinateScope':scope,'coordinateEvidence':coord,'inventoryEvidence':inv}
 spot=dict(common,id=id,name=name,lat=lat,lon=lon,resources=res,imageAsset=asset,seconds=start,direction=direction,method=method,kit=kit,risks=risks,verified=True,photoSHA256=sha(poster),photoSourceSeconds=start+1,photoMapOverlayVisible=False)
 guide=dict(common,sourceAcquisition='Approved local source cache; partial files used only within complete decodable intervals' if vid=='boGcZ2neH6g' else 'Approved complete local source cache',spotID=id,rightsBasis='licensed',rightsApproval='User confirmed licenses for all source videos',sourceWidth=1920,sourceHeight=1080,harvestDemonstrated=False,evidenceLimitations='Filmed region and resource view, not exact actor positions, guaranteed spawns or measured harvest yields. Coordinate view remains outside the clean preview. '+scope,steps=[{'id':base,'title':'Terrain & approach','loop':base,'poster':base,'startSeconds':start,'endSeconds':end,'sourceURL':url+'&t='+str(start)+'s','mapOverlayVisible':False,'inventoryOverlayVisible':False,'sha256':sha(clip),'visualReview':{'method':'Manual source context and encoded interval review at4fps','sourceFrameSeconds':[start+i/4 for i in range(int((end-start)*4))],'reviewedAt':'2026-10-07','result':'Clean terrain/resource/approach; no map or inventory obstruction','samplingLimit':'0.25-second sample review, not every-frame certification','contextSheet':str(sheet.relative_to(ROOT))}}])
 spots.append(spot);guides.append(guide);print(id,flush=True)
manifest={'schemaVersion':1,'createdAt':'2026-10-07','spots':spots,'guides':guides,'researchLimitations':['YouTube search connector API requests failed with API-key/parameter errors; saved search responses document this.','Authorized Extinction download returned HTTP403; no access controls were bypassed.','Partial source caches for other maps decode only opening sections; incomplete or map-obstructed extra regions were rejected.','Creator-caption-only coordinates were not promoted to new verified pins.','No ASE resource-map coordinates were copied into ASA pins.','All11 map planes were considered; this batch does not claim exhaustive verified coverage.'],'captionOnlyCandidates':[{'map':'astraeos','videoID':'k73mk3nz0wI','coordinates':[[27.6,46.5],[34.5,45.6]],'resource':'Crystal','reason':'Creator labels; raw camera GPS not readable'},{'map':'ragnarok','videoID':'0i0-XEV85m8','resources':['Black Pearls','Crystal','Metal','Obsidian','Organic Polymer','Silica Pearls','Sulfur'],'reason':'Multiple extra chapters have creator-label coordinates only; excluded from pins'}],'rejectedCandidates':[{'map':'scorched-earth','videoID':'k9IOWvnWMdg','lat':36.8,'lon':68.9,'gpsSeconds':59,'reason':'Hard cut at57s to the new region, source ends around61s; cannot supply continuous6sec clean clip'}]}
(ROOT/'tools/evidence/farming26-additions.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n')
