import json,pathlib,hashlib,subprocess
E=pathlib.Path('/Users/admin/Ascended-iPad-Dev/tools/evidence/farming34/ab-active-first');D=pathlib.Path('/Volumes/TONY SSD/ASCENDED_MEDIA/farming34/ab-active-first');S='/Volumes/TONY SSD/ASCENDED_MEDIA/farming34/browser-recording/TUoB8ouWPYk-active-2x.mp4'
def sha(p):
 with open(p,'rb') as f:return hashlib.file_digest(f,'sha256').hexdigest()
h=sha(S); rows=json.load(open(E/'draft-intervals.json'));out=[]
names=['Portal zipline metal outcrop','Portal mushroom plateau metal','Northwestern surface entrance metal cave','Blue Zone long slope metal','Eastern Blue Zone cavern metal','Element river bank obsidian','Fertile Lake western pillar pearls','Fertile Lake northern shallows pearls','Luminous Marsh lake pearls']
for (id,r,lat,lon,a,b,g),name in zip(rows,names):
 if id=='ab-portal-plateau-metal-418-345':g=60.8
 p=D/(id+'.mp4');poster=D/(id+'.jpg')
 subprocess.run(['ffmpeg','-v','error','-i',str(p),'-f','null','-'],check=True)
 metadata=json.loads(subprocess.check_output(['ffprobe','-v','error','-show_entries','format=duration:stream=codec_name,width,height,codec_type','-of','json',str(p)]))
 assert float(metadata['format']['duration'])>=6 and float(metadata['format']['duration'])<=10
 assert len(metadata['streams'])==1 and metadata['streams'][0]['codec_name']=='h264'
 evidence='Visible ore outcrops in the dedicated Metal chapter; no Rich Metal or guaranteed yield claim.' if r=='Metal' else ('Dark obsidian nodes beside Element river terrain in the dedicated Obsidian chapter.' if r=='Obsidian' else 'Visible rounded clam shell clusters on the lake bed in the dedicated Silica Pearls chapter.')
 out.append({'id':id,'map':'aberration','name':name,'resources':[r],'lat':lat,'lon':lon,'videoID':'TUoB8ouWPYk','startSeconds':round(.068941+2*(a-12.251),1),'endSeconds':round(.068941+2*(b-12.251),1),'coordinateEvidence':f'Creator explicitly captions {lat} LAT / {lon} LONG at captured movie~{g}s (source~{round(.068941+2*(g-12.251),1)}s), identifying this filmed farming region. Numeric creator caption used, not M-map cursor interpretation.','inventoryEvidence':evidence,'clipPath':str(p),'posterPath':str(poster),'sourceURL':'https://www.youtube.com/watch?v=TUoB8ouWPYk','sourcePlane':'aberration ASA coordinate plane','sourceCoordinateScope':'Creator-labelled farming region','mapOverlayVisible':False,'creatorInsetVisible':False,'inventoryOverlayVisible':False,'rightsBasis':'licensed','acquisitionState':'User-authorized licensed public Chrome playback captured in isolated native window; no denied download or authentication bypass','sourcePath':S,'sourceSHA256':h,'clipSHA256':sha(p),'posterSHA256':sha(poster),'visualReview':{'contactSheet':str(E/(id+'-contact.jpg')),'coordinateFrame':str(E/(id+'-coordinate.jpg')),'fullEncodedDecode':True,'sampleRateFPS':4,'continuousShot':True,'reviewed':True,'result':'Final encoded chronological4fps frames manually reviewed: continuous filmed terrain/resource scene, no map, caption, browser controls, inventory or edit cut. Full GPS proof retained separately.'},'visualReviewStatus':'verified','sourceCrop':{'x':0,'y':140,'width':1184,'height':526,'sourceWidth':1184,'sourceHeight':666,'reason':'Remove creator numeric and chapter captions; map frames excluded from intervals.'},'captureProvenance':{'captureFirstSampleUTC':'2026-10-08T05:12:34.963Z','playAnchorUTC':'2026-10-08T05:12:47.214Z','playAnchorSourceSeconds':.068941,'playbackRate':2,'movieStartSeconds':a,'movieEndSeconds':b,'gpsMovieSeconds':g,'sourceTimeFormula':'sourceSeconds=0.068941+2*(movieSeconds-12.251)','deliveryTiming':'Captured2x playback restored to natural speed with setpts2; source bounds approximate from observed play anchor, rounded0.1s.','captureSHA256':h},'evidenceLimitations':'Creator-labelled regional waypoint; no guaranteed node availability or yield. Source timing reconstructed from capture UTC/playback anchor and may drift slightly; exact capture clip bounds separately recorded. Cropping removes creator captions from delivery, full uncropped coordinate proof retained.','encodedDurationSeconds':float(metadata['format']['duration'])})
json.dump({'candidates':out,'rejected':[{'region':'Metal34.7/61.7','reason':'No clean6s continuous shot before/after map and edits.'},{'region':'Crystal/green gems source480–530','reason':'No numeric GPS caption for this patch in assigned source range; not inferred from earlier coordinates.'}]},open(E/'reviewed-additions.json','w'),indent=2)
for p in [D/'ab-blue-metal-347-617.mp4',D/'ab-blue-metal-347-617.jpg',E/'ab-blue-metal-347-617-contact.jpg',E/'ab-blue-metal-347-617-coordinate.jpg']:
 if p.exists():p.unlink()
for pat in ['metal-*.jpg','pearl-*.jpg','survey.jpg']:
 for p in E.glob(pat):p.unlink()
print('Verified',len(out),'candidates',h)
