import json,hashlib,math,subprocess
from pathlib import Path
p=Path('/Users/admin/Ascended-iPad-Dev/tools/evidence/farming34/lost-oil-independent');out=Path('/Volumes/TONY SSD/ASCENDED_MEDIA/farming34/lost-oil-independent');clock=json.loads((p/'capture-clock-evidence.json').read_text())
specs=[('lost-colony-safe-cave-oil-656-483',65,8,60,'Mountain ice cave oil rocks',65.6,48.3,'Creator explicitly narrates latitude65.6 longitude48.3 at source57–60s. Source59–60s native map shows65.6/48.3, greenplayer aligns mapgrid near65.6/48.3. White hostpointer near68/70 differs, so not mistaken for the displayedposition. Waypoint is creator caveapproach region, not every interior oilrock.','Oil rocks clearly filmed on cave floor, Ankylo strikes them through continuous65–73s. Source0s closeup establishes striped oilrock appearance; narrator identifies cave oil. No measured yield/count claimed.'),('lost-colony-central-river-oil-595-586',104.75,6,96,'Central canyon river oil rocks',59.5,58.6,'Creator explicitly narrates latitude59.5 longitude58.6 at source94–98s. Native map96s shows nearby59.5/58.5, greenplayer aligns grid around59.5/58.6, whitehostpointer far away. Pin uses exact spoken regional pair, not falsely relabelled exact native59.5/58.5 readout.','Ankylo visibly strikes striped oilrocks in river; narrator identifies these rocks at source100–108s. Recut begins after last first/thirdperson toggle104.75s and ends beforemap111s; no camera mode jump in delivery.')]
def sha(f):return hashlib.sha256(Path(f).read_bytes()).hexdigest()
c=[]
for id,t,d,gps,name,lat,lon,coords,proof in specs:
 clip=out/f'{id}.mp4';poster=out/f'{id}.jpg';dur=float(subprocess.check_output(['ffprobe','-v','error','-show_entries','format=duration','-of','csv=p=0',str(clip)]))
 c.append(dict(id=id,map='lost-colony',name=name,resources=['Oil'],lat=lat,lon=lon,videoID='LKOZNBaoCpc',startSeconds=t,endSeconds=t+d,coordinateEvidence=coords,inventoryEvidence=proof,clipPath=str(clip),posterPath=str(poster),sourceURL='https://www.youtube.com/watch?v=LKOZNBaoCpc',sourceTimestampURL='https://www.youtube.com/watch?v=LKOZNBaoCpc&t='+str(math.floor(t))+'s',sourcePlane='Lost Colony ASA coordinate plane',sourceCoordinateScope='Creator-spoken filmed farming region; native map/player grid corroboration; not exact oilactor positions',mapOverlayVisible=False,creatorInsetVisible=False,inventoryOverlayVisible=False,rightsBasis='licensed',acquisitionState='User-authorized licensed public Chrome playback captured in isolated native window; no denied download or authentication bypass',sourcePath=clock['sourcePath'],sourceSHA256=clock['sourceSHA256'],sourceCapture=clock,clipSHA256=sha(clip),posterSHA256=sha(poster),visualReview={'contactSheet':str(p/f'{id}-contact.jpg'),'coordinateFrame':str(p/f'{id}-coordinate.jpg'),'fullEncodedDecode':True,'sampleRateFPS':4,'continuousShot':True,'reviewed':True,'result':f'All{round(dur*4)} chronological4fps samples reviewed; continuous oilharvesting scene, no map/inventory/creator inset/caption/edit or perspective jump. Encodedclip fullydecoded exit0 withoutdiagnostics.'},evidenceLimitations='Independent standard ASA LostColony guide published8Jan2026, no mod/customserver statements observed in public metadata. Coordinates cover filmed region; no guaranteed yield or permanent spawn count. Source auto captions incorrectly say LostIsland in intro/outro; actual LostColony map/terrain, title, description and release date establish edition. '+('Spoken58.6 differs nearby native58.4–58.5 by0.1–0.2; retain regional scope.' if lon==58.6 else ''),visualReviewStatus='verified',sourceCrop={'x':0,'y':60,'width':1100,'height':520,'sourceWidth':1184,'sourceHeight':666,'reason':'Remove hotbar, top statusbar and right HUD/creatorlogo; retain oilnodes and activeharvest. Full uncropped coordinate frames retained.'},captureCut={'sourceStartSeconds':t,'sourceDurationSeconds':d,'captureStartSeconds':12.383+(t-.04244)/2,'captureDurationSeconds':d/2,'encodedDurationSeconds':dur,'naturalSpeedRestorationFactor':2},sourcePublishedDate='2026-01-08',sourceTitle='Where To Find Oil on Lost Colony in ARK Survival Ascended | Secret Oil Cave!',sourceCreator='ClickTockClock',vanillaCompatibility={'basis':'Fresh independent standardASA resourceguide shows normal LostColony game terrain/oilnodes and Ankylosaurus harvesting, with no customcave/serverpromotion in public metadata. Does not reuse uncertainRtRsourcecoords.','state':'independent-standard-ASA-footage','rtRCave69_46_4Compatibility':'Not cleared; distant creator pair not transplanted onto this independently located cave.'}))
existing=json.load(open('/Users/admin/Ascended-iPad-Dev/native/Ascended/Resources/verified-resource-spots.json'))['spots'];oil=[{k:s.get(k) for k in ['id','lat','lon','resources']} for s in existing if s['map']=='lost-colony' and 'Oil' in s['resources']]
(p/'reviewed-additions.json').write_text(json.dumps({'candidates':c,'heldCandidates':[],'reviewedSourceRangeSeconds':[0,140],'captureClockEvidence':str(p/'capture-clock-evidence.json'),'duplicateAudit':{'existingLostOilSpots':oil,'result':'Cave65.6/48.3 and centralriver59.5/58.6 are distinct from existing southwest river91.7/20.8. Two new regions, not second angles of same accepted region.'},'priorRtRComparison':{'heldCreatorPair':[69,46.4],'independentCavePair':[65.6,48.3],'observations':'Both icecave settings, but exact interior landmark match not established from available views; coordinate pairs differ. Do not promote or recount RtR69/46.4. Independent source can stand alone with its own explicit narratedposition and harvesting footage.'},'sourceEditionAudit':'Auto-caption LostIsland words conflict with explicit videoASA LostColony title/description and unmistakable nativeLostColony city/biomemap. Source metadata published8Jan2026 after LostColony release19Dec2025. Actual map is authority.','reviewerNote':'Two new Oil region candidates with6–8sec clean natural1x clips. No acquisition/browser/app changes in reviewer. Nativecapturewholedecode completed; nonmonotonic screen timestamps normalized in delivery clips.'},indent=2))
print('2 verified Oil regions written')
