import json,hashlib
from pathlib import Path
ROOT=Path('/Users/admin/Ascended-iPad-Dev');p=ROOT/'native/Ascended/Resources/verified-resource-spots.json';d=json.loads(p.read_text())
base=['Metal','Rich Metal','Crystal','Obsidian','Oil','Silica Pearls','Black Pearls','Cementing Paste','Organic Polymer','Polymer','Rare Flowers','Rare Mushrooms','Honey','Chitin','Keratin','Wood','Stone','Fiber','Thatch','Water','Flint','Element'];extra=['Sulfur','Sandpile','Cactus Sap','Clay','Silk','Salt'];coverage=[]
for m in ['ragnarok','the-island','the-center']:
 for k in base+(extra if m=='ragnarok' else []):
  ids=[s['id'] for s in d['spots'] if s['map']==m and (k in s['resources'] or (k=='Honey' and 'Giant Bee Honey' in s['resources']))]
  status='verified' if ids else 'pending';reason='Đã đối chiếu tọa độ và ảnh thật của vùng farm trong video.' if ids else 'Chưa đủ cảnh GPS và ảnh thu hoạch để xác minh vùng farm.'
  if k=='Polymer':status='crafting';reason='Chế tạo tại Fabricator: 2 Cementing Paste + 2 Obsidian cho 1 Polymer; Organic Polymer có thể thay thế theo công thức.'
  if k=='Clay':status='crafting';reason='Chế tạo tại Mortar and Pestle: 2 Sand + 1 Cactus Sap cho 2 Clay; không gán pin chế tạo thành node tự nhiên.'
  if k=='Element':status='boss';reason='Nhận Element từ boss tương ứng của bản đồ; cần Artifact, tribute và đội hình. Không phải node tài nguyên tự nhiên.'
  coverage.append(dict(map=m,resource=k,status=status,spotIDs=ids,reason=reason))
assert len({s['id'] for s in d['spots']})==len(d['spots'])
for s in d['spots']:
 a=ROOT/'native/Ascended/Assets.xcassets'/(s['imageAsset']+'.imageset');f=json.loads((a/'Contents.json').read_text())['images'][0]['filename'];assert hashlib.sha256((a/f).read_bytes()).hexdigest()==s['photoSHA256'];assert 0<=s['lat']<=100 and 0<=s['lon']<=100;assert isinstance(s['seconds'],(int,float));assert s['coordinateEvidence'] and s['inventoryEvidence']
for c in coverage:
 if c['resource']=='Keratin' and c['map'] in ['the-island','the-center']:
  c.update(status='creature',reason='Săn Carbonemys, Triceratops, Stegosaurus hoặc Ankylosaurus, rồi thu hoạch xác bằng Metal Hatchet hay thú phù hợp. Chitin có thể thay Keratin trong công thức ghi Chitin/Keratin; hãy kiểm tra công thức riêng.',videoID='LIlgVYn8Fag',seconds=133.5,sourceURL='https://www.youtube.com/watch?v=LIlgVYn8Fag',imageAsset='FarmPhoto-acquisition-keratin',method='Dùng Metal Hatchet thu hoạch xác; chọn Carbonemys ven bờ khi mới bắt đầu, tránh Stegosaurus hoặc Ankylosaurus nếu chưa đủ sức.',kit=['Metal Hatchet','Argentavis','Therizinosaurus'],risks=['Sinh vật di chuyển','Bầy thú có thể phản công'],coordinateEvidence='No GPS or Center location is claimed. The actual ASA Island resource guide is used for general Keratin mechanics only.',inventoryEvidence='Source Keratin explanation around103–141s shows actual ASA Carbonemys/Trike/Ankylosaurus footage; screenshot133.5s depicts Ankylosaurus. No per-kill harvest, measured yield or location is claimed.',mechanicsSourceURL='https://ark.wiki.gg/wiki/Keratin')
  if c['map']=='the-center':c['reason']+=' Video minh họa cơ chế bằng cảnh The Island, không xác nhận vị trí tại The Center.'
 if c['resource']=='Chitin' and c['map']=='ragnarok' and c['status']=='pending':
  c.update(status='creature',reason='Thu hoạch xác Karkinos hoặc Iceworm bằng Chainsaw; chuẩn bị vũ khí và giáp trước khi vào hang. Đây là phương pháp săn sinh vật, chưa có pin GPS của đoạn farm.',videoID='5IhlD3yzqjU',seconds=676.5,sourceURL='https://www.youtube.com/watch?v=5IhlD3yzqjU',imageAsset='FarmPhoto-acquisition-rag-chitin',method='Giết Karkinos bằng thú chiến đấu phù hợp rồi dùng Chainsaw thu hoạch xác; giữ đường rút khỏi hang.',kit=['Chainsaw','Pump-Action Shotgun','Fur Armor'],risks=['Karkinos có thể kẹp người hoặc thú','Iceworm và lạnh nếu chọn hang băng'],coordinateEvidence='No GPS pin is claimed. Source farming method chapter626–706s lacks literal farm GPS.',inventoryEvidence='Actual Karkinos corpse673.5–682.5s is harvested with Chainsaw; screenshot676.5s displays Chitin+1569, Organic Polymer+564 and Raw Meat+209 overlay. These are creator yield examples, not promised vanilla-save amounts.',mechanicsSourceURL='https://ark.wiki.gg/wiki/Chitin')
 if c['map']=='the-center' and c['resource']=='Black Pearls' and c['status']=='pending':
  c.update(status='creature',reason='Săn Alpha Mosasaur hoặc Alpha Tusoteuthis rồi lấy loot từ xác; Eurypterid là nguồn nhỏ hơn. Video minh họa sinh vật, không xác nhận vùng spawn hoặc GPS tại The Center.',videoID='SHb-iMDtk7k',seconds=333,sourceURL='https://www.youtube.com/watch?v=SHb-iMDtk7k',imageAsset='FarmPhoto-center-blackpearls-alpha-mosa',method='Dùng đội thú biển đã chuẩn bị đủ sức để đánh bại Alpha Mosasaur; kiểm tra inventory xác hoặc túi loot trước khi thu hoạch hết.',kit=['SCUBA Tank','SCUBA Flippers','Mosasaurus','Tusoteuthis'],risks=['Alpha Mosasaur rất mạnh','Thiếu oxy','Sinh vật di chuyển và spawn thay đổi'],coordinateEvidence='No location or GPS claim. Source survey uses admin/mod tools and natural versus manually spawned status cannot be independently established. The former35.19/95.77 GPS point was removed from verified spots.',inventoryEvidence='Actual source frame333s illustrates Alpha Mosasaur. Player BlackPearl101 at350s was already carried and is not harvest proof. Legitimate obtaining mechanism independently supported by official Wiki Black Pearl; source admin-killing behavior is not recommended.',mechanicsSourceURL='https://ark.wiki.gg/wiki/Black_Pearl')
 if c.get('imageAsset'):
  a=ROOT/'native/Ascended/Assets.xcassets'/(c['imageAsset']+'.imageset');n=json.loads((a/'Contents.json').read_text())['images'][0]['filename'];c['photoSHA256']=hashlib.sha256((a/n).read_bytes()).hexdigest()
d['coverage']=coverage;p.write_text(json.dumps(d,ensure_ascii=False,indent=2))
report=ROOT/'docs/codex-reports/2026-10-04-resource-video-research.json';q=json.loads(report.read_text());q.update(verifiedSpots=len(d['spots']),coverage=coverage,remainingUnverified=[c for c in coverage if c['status']=='pending'],assetValidation='All image SHA256 values, unique spot IDs, numeric timestamps and GPS bounds verified.',sourceVideos=sorted({s['videoID'] for s in d['spots']} | {c['videoID'] for c in coverage if c.get('videoID')}));report.write_text(json.dumps(q,ensure_ascii=False,indent=2));print(len(d['spots']),'spots; pending',[(c['map'],c['resource']) for c in coverage if c['status']=='pending'])
