"""Build the curated Island route using explicit source-to-goal references."""
import json
from pathlib import Path
root=Path(__file__).resolve().parents[1]; resources=root/'native/Ascended/Resources'
items=json.loads((resources/'equipment-library.json').read_text())['items']
facts=json.loads((resources/'visual-facts.json').read_text())
sources=[]
def source(id,title,url,kind,note):
 sources.append(dict(id=id,title=title,url=url,kind=kind,note=note,reviewedAt='2026-10-08'));return id
s1=source('player-start','Smilloww + PvE players · Island game plan','https://www.reddit.com/r/ArkSurvivalAscended/comments/1ebsdc8/ark_beginner_guide/','Player experience','Starter shelter, utility tames and travel. Community recommendations; unsafe escape advice and outdated fire-resistance claims excluded.')
s2=source('player-route','ASA players · First playthrough advice','https://www.reddit.com/r/ArkSurvivalAscended/comments/1u7so02/first_time_player_a_bit_of_direction_a_few_tips/','Player experience','Flyer → gatherers → crafting base; Baryonyx/Thylacoleo cave options. Route milestones and quantities are our planning choices.')
s3=source('player-balance','Small-tribe players · Exploring while progressing','https://www.reddit.com/r/ArkSurvivalAscended/comments/1uyvy56/how_to_progress_on_the_island_map_with_a_very/','Player experience','Ocean progression and mixed-purpose tames alongside boss preparation; Therizinos can use cakes.')
s4=source('player-order','Solo players · Which boss first?','https://www.reddit.com/r/ARK/comments/1828e5h/easiest_boss/','Player experience','Megapithecus is often easier in combat; Broodmother can come first when its artifacts and a suitable army are ready. Opinions, not a forced order.')
s5=source('player-current','ASA players · Current boss teams','https://www.reddit.com/r/ARK/comments/1sq9zqq/best_boss_fighters_now/','Player experience','Therizino/Yuty remains a player option; newer teams exist. Recent players warn that old Alpha Dragon advice is insufficient.')
s6=source('wiki-brood','ARK Wiki · Broodmother','https://ark.wiki.gg/wiki/Broodmother_Lysrix','Mechanics reference','Hunter + Clever + Massive; Megatherium insect buff; 20-tame arena limit. Rex/Th eri alternatives are possible.'.replace('Th eri','Theri'))
s7=source('wiki-monkey','ARK Wiki · Megapithecus','https://ark.wiki.gg/wiki/Megapithecus','Mechanics reference','Brute + Devourer + Pack. Keep the fight away from the arena drop-off.')
s8=source('wiki-dragon','ARK Wiki · Dragon','https://ark.wiki.gg/wiki/Dragon','Mechanics reference','Percent-health fire breath affects herbivores too. Protect the rider from minions and avoid assuming saddle armor stops burn damage.')
s9=source('wiki-breeding','ARK Wiki · Breeding','https://ark.wiki.gg/wiki/Breeding','Mechanics reference','Inherit parental natural stats, not player-added levels. Page flags ASA update gaps; no mutation formula or fixed breeding timer imported.')
s10=source('wiki-imprint','ARK Wiki · Imprinting','https://ark.wiki.gg/wiki/Imprinting','Mechanics reference','Raised fighters retain imprint stat bonuses; rider bonus requires the imprinter to ride. No assumption of rider bonus on an entire AI army.')
s11=source('wiki-tek','ARK Wiki · Tek Cave','https://ark.wiki.gg/wiki/Tek_Cave','Mechanics reference','Volcano entry, lava path and time-limited entrance. No reliance on cryopod releases inside the cave.')
s12=source('wiki-overseer','ARK Wiki · Overseer','https://ark.wiki.gg/wiki/Overseer','Mechanics reference','Gamma entry requires the three Gamma guardian trophies or higher-tier equivalents, and level 60. Beta/Alpha require additional tribute.')
s13=source('wiki-deino','ARK Wiki · Deinosuchus changes','https://ark.wiki.gg/wiki/Deinosuchus','Patch cross-check','Patch 73.13 removes boss bleed. Older bleed shortcuts excluded from this route.')
s14=source('cake-recipe','Beacon · ASA cake recipe','https://usebeacon.app/Games/ArkSA/Mods/2399830/PrimalItemConsumable_SweetVeggieCake_C','Game-data reference','Honey, sap, crops, stimulant, fibre and water. Craft in a Cooking Pot or Industrial Cooker; keep a continuing supply.')
s15=source('wiki-basilo','ARK Wiki · Basilosaurus','https://ark.wiki.gg/wiki/Basilosaurus','Mechanics reference','Shock/grab immunity supports ocean runs; pressure damage at depth and cave predators still require preparation.')
s16=source('player-swamp-video','BEYPlaysGames · Island paste routes','https://www.youtube.com/watch?v=ThiYu0M6a_A','Reviewed gameplay','Previously reviewed source footage shows a mounted Beelzebufo harvesting paste in Swamp Cave. Cave access and protection remain essential.')
s17=source('wiki-caves','ARK Wiki · Island cave routes','https://ark.wiki.gg/wiki/Caves','Mechanics reference','Cave/artifact associations and route-specific hazards; ASA entrances differ from ASE, so use the existing Island cave and Atlas records for coordinates.')
phases=[]
def goal(id,title,visual,detail,refs,optional=False,count=None):
 if visual.startswith(('Dino-','Nav-','Artifact-','Cutout-','MapLogo-')): asset=visual
 else:
  found=next((i for i in items+facts if i['name'].lower()==visual.lower()),None)
  if not found or not found.get('asset'): raise ValueError(visual)
  asset=found['asset']
 if not (root/'native/Ascended/Assets.xcassets'/(asset+'.imageset')).exists(): raise ValueError(asset)
 return dict(id=id,title=title,asset=asset,detail=detail,sourceIDs=refs,optional=optional,quantity=count)
def panel(id,title,icon,goals):return dict(id=id,title=title,icon=icon,goals=goals)
def phase(id,title,subtitle,asset,note,groups):phases.append(dict(id=id,title=title,subtitle=subtitle,asset=asset,note=note,groups=groups))
g=goal;p=panel
phase('shore','Beach Home','Survive · settle · enjoy the coast','MapLogo-the-island','Choose Moschops OR Parasaur. A small starter home is enough.',[
p('creatures','Creatures','creatures',[g('starter','Starter companion','Dino-moschops','Choose one: Moschops for gathering or Parasaur for carrying. Check the requested food before taming Moschops.',[s1,s2]),g('parasaur','Parasaur option','Dino-parasaur','Alternative starter; not a second required tame.',[s1],True)]),
p('base','Base','locations',[g('shore-home','Coastal cottage','Nav-base','Suggested layout: sheltered bed + crafting corner + labelled storage. Pick a southern beach you enjoy.',[s1,s2]),g('bed','Respawn ready','Simple Bed','Place a bed in your shelter before longer trips.',[s1]),g('fire','Food & light','Campfire','Keep cooked food and an accessible light source.',[s1])]),
p('equipment','Equipment','tools',[g('starter-tools','Pick + hatchet','Stone Pick','Craft both tools; use pick for flint/thatch and hatchet for stone/wood.',[s1]),g('bola','Bolas + bow','Bola','Carry bolas and a bow for early taming and small-predator defence.',[s1])]),
p('adventure','Adventure','spawn',[g('coast-scout','Explore your coast','Nav-map','Scout nearby water and a first metal route; skip the swamp until prepared.',[s1,s2]),g('pretty-camp','Make it yours','Storage Box','Optional: porch, storage labels or a favourite tame. A leisure milestone, not a game unlock.',[s3],True)])])
phase('flight','First Flight','Mobility · metal · gathering team','Dino-argentavis','Saddles and carrying rules matter. Argentavis carrying depends on PvE settings.',[
p('creatures','Creatures','creatures',[g('ptera','Pteranodon','Dino-pteranodon','First scouting flyer; stamina and safe landing matter.',[s2]),g('argy','Argentavis','Dino-argentavis','Cargo flyer for the next base and resource trips.',[s1,s2]),g('anky','Ankylosaurus','Dino-ankylosaurus','Metal gatherer; pair with Argentavis when carrying is allowed.',[s1,s2]),g('doed','Doedicurus','Dino-doedicurus','Stone supply for the permanent home.',[s2])]),
p('base','Base','locations',[g('workshop','Stone workshop','Refining Forge','Upgrade the vulnerable starter shell and leave room for forges and a smithy.',[s1]),g('smithy','Crafting corner','Smithy','Store metal near the forge/smithy; this layout is a convenience plan.',[s2])]),
p('equipment','Equipment','tools',[g('metal-tools','Metal tools','Metal Pick','Craft a Metal Pick and Metal Hatchet before repeated mining trips.',[s1]),g('taming-kit','Crossbow + tranqs','Crossbow','Carry tranq arrows, narcotics, food and the appropriate saddle for your tame.',[s1,s2]),g('spyglass','Scout levels','Spyglass','Check a target before committing resources; tame level alone does not prove good breeding stats.',[s2,s9])]),
p('adventure','Adventure','spawn',[g('metal-run','First metal loop','Nav-farming','Choose a filmed Island Metal location in Farming and complete one return trip.',[s2]),g('flight-home','Return alive','Nav-map','Learn a safe flyer route between your home and a resource region.',[s2])])])
phase('home','A Base to Keep','Beautiful home · production · nursery','Nav-base','Suggested build: home + workshop + tame yard + greenhouse. No giant mansion required.',[
p('creatures','Creatures','creatures',[g('wood-gatherer','Wood gatherer','Dino-castoroides','Optional wood specialist; a Therizinosaur can cover several jobs later.',[s1,s3],True),g('theri-parents','Therizino parents','Dino-therizinosaur','Find a male/female pair with useful health and melee. Keep this pair safe.',[s3,s5,s9],count='1 pair')]),
p('base','Base','locations',[g('main-home','Home + tame yard','Nav-base','Build a stone home you like with room for useful tames; browse Base Locations for a site.',[s2,s3]),g('fabricator','Powered workshop','Fabricator','Fabricator, powered generator and refrigerator; make a reliable fuel supply.',[s2]),g('greenhouse','Crop corner','Large Crop Plot','Plant cake crops and narcoberries; greenhouse styling is optional.',[s3,s14]),g('nursery','Nursery + trough','Feeding Trough','Separate breeding and raising space from your fighting animals.',[s9])]),
p('equipment','Equipment','tools',[g('hatch','Incubation setup','Air Conditioner','Match temperature to the egg; several AC units may be needed, depending on placement and climate.',[s9]),g('cake-supply','Honey + sap','Bee Hive','Establish honey, sap and cake crops; keep a Cooking Pot or Industrial Cooker, stimulant, fibre and water.',[s3,s14]),g('big-forge','Industrial Forge','Industrial Forge','Optional major upgrade once metal demand grows; not required to start caves.',[s2],True)]),
p('adventure','Adventure','spawn',[g('resource-tour','Resource tour','Nav-farming','Visit crystal, oil and paste regions while collecting supplies for your new home.',[s2,s3]),g('home-style','A favourite corner','Nav-base','Optional: balcony, greenhouse entrance or a scenic landing pad.',[s3],True)])])
phase('explore','Caves & Ocean','Artifacts · blueprints · new biomes','Nav-caves','Prepare per cave. A Baryonyx does not fit or solve every cave.',[
p('creatures','Creatures','creatures',[g('bary','Baryonyx','Dino-baryonyx','Breed or tame a dependable cave mount for routes it can enter.',[s2]),g('basilo','Basilosaurus','Dino-basilosaurus','Prepare an ocean mount for underwater artifact routes; depth and dangerous spawns still matter.',[s3,s15]),g('frog','Swamp farmer','Dino-beelzebufo','Optional: Beelzebufo paste farming; Megatherium is another chitin option. Check cave access first.',[s16,s6,s17],True)]),
p('base','Base','locations',[g('outpost','Cave staging kit','Hide Sleeping Bag','Keep a spare kit and a safe respawn point outside your chosen route.',[s2]),g('loot-store','Blueprint storage','Storage Box','Protect useful saddle and weapon blueprints for army crafting.',[s5])]),
p('equipment','Equipment','tools',[g('cave-kit','Armour + recovery','Medical Brew','Pack spare armour, healing, ammunition and route-specific protection.',[s8]),g('gas-mask','Swamp protection','Gas Mask','Prepare poison protection before Swamp Cave; do not enter in ordinary armour alone.',[s17]),g('scuba','Ocean kit','SCUBA Tank','Prepare oxygen gear and a way to recover if the mount is lost.',[s3]),g('fur','Snow kit','Fur Chestpiece','Use cold protection for northern exploration and snow-cave preparation.',[s2])]),
p('adventure','Adventure','spawn',[g('first-cave','First cave route','Artifact-hunter','Complete Lower South Cave for Artifact of the Hunter; use the existing cave walkthrough.',[s6]),g('ocean-run','First ocean route','Artifact-brute','Work toward Artifact of the Brute in Caverns of Lost Faith; do not rush the underwater caves.',[s7]),g('loot-run','Blueprint trips','Nav-equipment','Run suitable cave/drop routes repeatedly until you can craft better saddles.',[s5])])])
phase('army','Raise Your Army','Good parents · imprints · equipment','Dino-therizinosaur','Suggested shared team: 19 Therizinos + 1 ridden Yuty. Preserve parents; use raised offspring.',[
p('creatures','Creatures','creatures',[g('theri-army','Raised Therizinos','Dino-therizinosaur','Build a shared fighter line with useful health/melee; imprint and level the battle offspring. 19 is a planning roster, not a minimum-win guarantee.',[s3,s5,s9,s10],count='19'),g('yuty','Yutyrannus','Dino-yutyrannus','Ride for courage roar and whistles; level useful health/stamina.',[s6],count='1'),g('mega-option','Broodmother option','Dino-megatherium','Optional specialist army. Replace Therizinos rather than adding beyond the arena cap.',[s6],True),g('pig-option','Healing option','Dino-daeodon','Optional healer replaces one fighter: 18 + Yuty + Daeodon. Pack food and assess the DPS trade-off.',[s5],True)]),
p('base','Base','locations',[g('safe-parents','Safe breeders','Nav-base','Keep original breeding parents and spare offspring at home.',[s9]),g('army-yard','Army staging yard','Feeding Trough','Enough space to saddle, heal and organise every fighter before departure.',[s9])]),
p('equipment','Equipment','tools',[g('saddles','Saddle each fighter','Nav-equipment','Craft quality saddles from your blueprints; verify the actual armour stat.',[s5,s6]),g('cakes','Cake production','Sweet Vegetable Cake','Carry cakes on Therizinos. They heal eligible herbivores; they do not cancel Dragon burn.',[s3,s8,s14]),g('backup-gun','Backup shotgun','Pump-Action Shotgun','Carry a usable firearm, ammunition, armour and Medical Brews for rider emergencies.',[s8])]),
p('adventure','Practice','stats',[g('whistles','Whistle rehearsal','Dino-yutyrannus','Practise follow groups, stop, attack and courage roar before teleporting.',[s6]),g('team-check','Roster check','Nav-creatures','Check saddles, health, food and position inside the teleport radius; ordinary arenas cap the team at 20.',[s6])])])
phase('guardians','First Guardians','Gamma · learn · recover','Cutout-Boss-megapithecus','Suggested order: Megapithecus → Broodmother. Swap them if the spider set and army are ready first.',[
p('creatures','Army','creatures',[g('healthy-team','Healed battle team','Dino-therizinosaur','Use your raised/saddled team; keep the Yuty rider clear of the front line.',[s6,s7]),g('after-fight','Recover between fights','Feeding Trough','Heal survivors and replace losses before another summon.',[s5])]),
p('base','Base','locations',[g('boss-storage','Tribute locker','Storage Box','Keep separate labelled boxes for each boss set and protect the trophies after victory.',[s6,s7,s12]),g('trophy-room','Trophy corner','Nav-base','Optional: build a display for the guardians you defeat.',[s3],True)]),
p('equipment','Artifact sets','loot',[g('brute','Artifact of the Brute','Artifact-brute','Megapithecus tribute.',[s7]),g('devourer','Artifact of the Devourer','Artifact-devourer','Megapithecus tribute.',[s7]),g('pack','Artifact of the Pack','Artifact-pack','Megapithecus tribute.',[s7]),g('hunter','Artifact of the Hunter','Artifact-hunter','Broodmother tribute.',[s6]),g('clever','Artifact of the Clever','Artifact-clever','Broodmother tribute.',[s6]),g('massive','Artifact of the Massive','Artifact-massive','Broodmother tribute.',[s6])]),
p('adventure','Boss goals','stats',[g('monkey-gamma','Gamma Megapithecus','Cutout-Boss-megapithecus','Bait toward a safe fight position; keep the army away from the drop-off.',[s7,s4]),g('brood-gamma','Gamma Broodmother','Cutout-Boss-broodmother','Keep fighters engaged; specialist Megatheriums need their insect buff. Save the trophy.',[s6]),g('harder-guardians','Beta / Alpha later','Nav-bosses','Optional after a clean Gamma: review current team, saddle quality and the exact higher-tier tribute.',[s5,s6,s7],True)])])
phase('dragon','Face the Dragon','Fire control · rider safety · Gamma','Cutout-Boss-dragon','Cakes are healing, not fire immunity. Gamma success is not proof of Alpha readiness.',[
p('creatures','Army','creatures',[g('dragon-team','Therizino team','Dino-therizinosaur','Recover the shared army, restock cakes and check combat stats. No universal HP/melee number guarantees this fight.',[s5,s8]),g('dragon-yuty','Support rider','Dino-yutyrannus','Maintain courage and control positioning; avoid bringing the support mount into the breath cone.',[s8])]),
p('base','Base','locations',[g('restock','Cake & repair stock','Sweet Vegetable Cake','Maintain the crop/honey/sap loop and a reserve equipment kit.',[s3,s8,s14]),g('keep-home','Keep your home safe','Nav-base','Leave parents and useful gathering tames behind.',[s9])]),
p('equipment','Artifact set','loot',[g('cunning','Artifact of the Cunning','Artifact-cunning','Dragon tribute; underwater cave preparation matters.',[s8]),g('immune','Artifact of the Immune','Artifact-immune','Dragon tribute; prepare Swamp Cave protection.',[s8]),g('skylord','Artifact of the Skylord','Artifact-skylord','Dragon tribute; use its route-specific cave guide.',[s8]),g('strong','Artifact of the Strong','Artifact-strong','Dragon tribute; prepare for the difficult Snow Cave.',[s8])]),
p('adventure','Boss goals','stats',[g('dragon-gamma','Gamma Dragon','Cutout-Boss-dragon','Review the fire-breath approach, protect the rider from Dimorphodons and keep the army clear of lava.',[s8]),g('dragon-higher','Beta / Alpha later','Nav-bosses','Optional: inspect the current strategy and tribute before harder tiers. Older boss-bleed shortcuts are no longer valid.',[s5,s8,s13],True)])])
phase('ascend','The Island Complete','Tek Cave · Overseer · keep the memories','Cutout-Boss-overseer','Gamma route: 3 guardian trophies + level 60. Prepare the cave separately from the arena.',[
p('creatures','Army','creatures',[g('tek-line','Practised convoy','Dino-therizinosaur','Use follow groups and manageable spacing through lava paths; plan a ground team that qualifies for the arena.',[s11]),g('tek-spares','Spare line at home','Nav-creatures','Keep breeders and replacement fighters safe; do not assume cryopods can deploy inside Tek Cave.',[s9,s11])]),
p('base','Base','locations',[g('volcano-stage','Volcano staging','Nav-base','Prepare supplies and an organised approach outside the cave without blocking the entry.',[s11]),g('finish-home','A home worth keeping','MapLogo-the-island','Optional: take a screenshot of the base and tames you raised along the way.',[s3],True)]),
p('equipment','Entry & kit','loot',[g('three-trophies','3 guardian trophies','Nav-bosses','For Gamma: Broodmother, Megapithecus and Dragon Gamma trophies (or higher equivalents), plus level 60.',[s12],count='3'),g('tek-kit','Heat + cold + repair','Fur Chestpiece','Pack temperature protection, spare armour, healing, a shotgun and enough ammunition for the route.',[s11]),g('tek-ammo','Backup ammunition','Simple Shotgun Ammo','Set your supply budget from the strategy you actually use; there is no universal minimum.',[s11])]),
p('adventure','Final goals','stats',[g('tek-route','Clear Tek Cave','Nav-caves','Enter within the opening window, keep fighters off lava and continue through the route to the terminal.',[s11]),g('overseer','Defeat Overseer','Cutout-Boss-overseer','Complete Gamma ascension; finish the experience before deciding whether to repeat harder tiers.',[s12]),g('higher-ascension','Beta / Alpha goal','Nav-bosses','Optional: obtain matching higher-tier guardian trophies and additional apex tribute first.',[s12],True)])])
pack=dict(mapID='the-island',title='Survival Guide',reviewedAt='2026-10-08',mode='PvE · solo / small tribe',approach='Explore, build a home, then ascend.',editorialNote='A suggested route, not a speedrun or a required tame list. Mark your own progress; no game connection. Creature choices, build layouts and roster quantities are planning recommendations.',sources=sources,phases=phases)
(resources/'the-island-survival-guide.json').write_text(json.dumps(pack,ensure_ascii=False,indent=2)+'\n')
print(len(phases),'phases;',sum(len(g['goals']) for p in phases for g in p['groups']),'goals;',len(sources),'sources')
