import json,hashlib,math,subprocess
from pathlib import Path
p=Path('/Users/admin/Ascended-iPad-Dev/tools/evidence/farming34/lost-active');out=Path('/Volumes/TONY SSD/ASCENDED_MEDIA/farming34/lost-active');clock=json.loads((p/'capture-clock-evidence.json').read_text())
def sha(f):return hashlib.sha256(Path(f).read_bytes()).hexdigest()
specs=[('lost-colony-river-metal-crystal-859-313',59,8,56,'Southern river metal and crystal deposits',['Metal','Crystal'],85.9,31.3,'Native bottom playerGPS LATITUDE85.9 LONGITUDE31.3 clear at source56s, directly before uninterrupted river mining region shot. Cursor position not used.','Gold metal-bearing rocks and white crystal clusters visible throughout river flythrough; metal pick harvest follows in same river segment source68–72s. No inventory/yield claim.'),('lost-colony-oil-cave-69-464',564,8,83,'Icy cave oil rocks',['Oil'],69,46.4,'Creator displays numeric pair69 &46.4 at source83s over this icy cave in dedicated Oil chapter. Pair interpreted in conventional latitude/longitude order; no separate nativeGPS axis readout shown. Same distinctive ice pillars and black rocks in longer outro flythrough.','Black irregular oil rocks visibly situated among cave ice pillars; creator Oil narration source78–83s identifies this cave as oil site. Outro reuses same identifiable cave flythrough with longer continuous shot. No measured yield.'),('lost-colony-river-metal-crystal-474-761',39,8,35,'Eastern river metal and crystal deposits',['Metal','Crystal'],47.4,76.1,'Native bottom playerGPS at source35s. Longitude76.1 clear; latitude appears47.4 but tree/snow partly obscures translucent map. HOLD until exact independent read, no coordinate invented.','Metal rock pick harvest and white crystal clusters visible in continuous same locale. No RichMetal classification inferred from goldveins.')]
good=[];held=[]
for id,t,ds,gps,name,res,lat,lon,coords,proof in specs:
 clip=out/f'{id}.mp4';poster=out/f'{id}.jpg';dur=float(subprocess.check_output(['ffprobe','-v','error','-show_entries','format=duration','-of','csv=p=0',str(clip)]))
 c=dict(id=id,map='lost-colony',name=name,resources=res,lat=lat,lon=lon,videoID='Oxyw-jv19xQ',startSeconds=t,endSeconds=t+ds,coordinateEvidence=coords,inventoryEvidence=proof,clipPath=str(clip),posterPath=str(poster),sourceURL='https://www.youtube.com/watch?v=Oxyw-jv19xQ',sourceTimestampURL=f'https://www.youtube.com/watch?v=Oxyw-jv19xQ&t={t}s',sourcePlane='Lost Colony ASA coordinate plane',sourceCoordinateScope='Creator/source camera filmed region, not exact individual resource actors',mapOverlayVisible=False,creatorInsetVisible=False,inventoryOverlayVisible=False,rightsBasis='licensed',acquisitionState='User-authorized licensed public Chrome playback captured in isolated native window; no denied download or authentication bypass',sourcePath=clock['sourcePath'],sourceSHA256=clock['sourceSHA256'],sourceCapture=clock,clipSHA256=sha(clip),posterSHA256=sha(poster),visualReview={'contactSheet':str(p/f'{id}-contact.jpg'),'coordinateFrame':str(p/f'{id}-coordinate.jpg'),'fullEncodedDecode':True,'sampleRateFPS':4,'continuousShot':True,'reviewed':True,'result':'32 chronological4fps encoded frames manually reviewed: continuous terrain/resource shot, no map/inventory/caption/creator inset/cut. Entire encoded file decoded without errors.'},evidenceLimitations='Source published12Jan2026; no permanent node count, guaranteed yield or exact actor coordinates. '+('Oil pair has no explicit LAT/LON axes; conventional order interpreted, exact creator pair retained.' if 'Oil' in res else ''),visualReviewStatus='verified',sourceCrop={'x':0,'y':76,'width':1184,'height':514,'sourceWidth':1184,'sourceHeight':666,'reason':'Remove YouTube recommendation banners at top and hotbar/creator logo at bottom; uncropped numeric coordinate proof separately retained.'},captureCut={'sourceStartSeconds':t,'sourceDurationSeconds':ds,'captureStartSeconds':8.743+(t-.046994)/2,'captureDurationSeconds':ds/2,'encodedDurationSeconds':dur,'naturalSpeedRestorationFactor':2},sourcePublishedDate='2026-01-12',sourceTitle='ALLE RESSOURCEN | FARMGUIDE | So FARMST du richtig auf Lost Colony | ASA',sourceCreator='RtRFinch')
 if id.endswith('474-761'):
  c['integrationState']='hold';c['holdReason']='Latitude partly obscured; exact independent read required';c['visualReviewStatus']='coordinate-review-required';held.append(c)
 else:good.append(c)
audit=[{'resource':r,'status':'no-addition','reason':reason} for r,reason in [('Black Pearls','Blood-water city harvest demonstration has no numerical siteGPS; two existing native sources already establish other regions.'),('Silica Pearls','Underwater whip/Thrall harvesting footage, no direct numericalGPS for underwater site; adjoining lake may match first region but geographic linkage and latitude require stronger proof.'),('Cementing Paste','Narrator says few beaver dams, cave insects as craft inputs; no geographic GPS or demonstrated direct paste yield. Do not classify ordinary creaturekill as CementingPaste.'),('Chitin','Cave creature farming method with no numerical siteGPS or completed relevant harvest.'),('Rich Metal','Metal chapter gold-bearing rocks visible, source does not label RichMetal; ordinaryMetal yield/appearance alone not enough for this distinction.'),('Obsidian','Dark rock pick footage source50–54s too short and first latitude obscured; no full6–10s uniquely identified clean obsidian site.'),('Rare Flowers','Rose-like flower harvesting footage372–383s but no numerical siteGPS.'),('Rare Mushrooms','Blue flower/plant method source383–390s but no numerical siteGPS; cannot assign arbitrary corrupted biome coordinates.'),('Organic Polymer','Same blue plants harvested byDireBear, inventory source391–393s; no numerical GPS for location.'),('Giant Bee Honey','Hive footage393–408s, including multiple stacked hives warning, no numerical GPS; unnamed distance marker not coordinates.'),('Sap','Two tree methods408–433s, no numerical siteGPS; no reuse of previous region coordinates for later edited locale.')]]
existing=json.load(open('/Users/admin/Ascended-iPad-Dev/native/Ascended/Resources/verified-resource-spots.json'))['spots'];existing=[{k:s.get(k) for k in ['id','lat','lon','resources']} for s in existing if s['map']=='lost-colony']
(p/'reviewed-additions.json').write_text(json.dumps({'candidates':good,'heldCandidates':held,'reviewedSourceRangeSeconds':[0,594.261],'captureClockEvidence':str(p/'capture-clock-evidence.json'),'duplicateAudit':{'existingSpots':existing,'result':'Confirmed southern river and oilcave different from same-resource existing regions. First eastern region stillcoordinate hold.'},'curatedResourceAudit':audit,'reviewerNote':'Two delivered candidates covering3resource types; one held candidate with ambiguous latitude. No invented unavailable/absence claims from lack of GPS footage.'},indent=2))
print('2deliverables+1held',[(c['id'],c['captureCut']['encodedDurationSeconds']) for c in good])

# Final mandatory vanilla compatibility gate: do not regenerate approved candidates.
f=p/'reviewed-additions.json';data=json.loads(f.read_text())
for item in data['candidates']:
 item['integrationState']='hold';item['visualReviewStatus']='source-compatibility-pending';item['holdReason']='Custom Caves / Sophisticated Systems creator promotion; exact vanilla site compatibility unverified.'
data['heldCandidates']+=data['candidates'];data['candidates']=[];data['sourceCompatibilityAudit']=str(p/'vanilla-compatibility-audit.json');data['reviewerNote']='All sites held pending exact vanilla compatibility proof or exact latitude read.'
f.write_text(json.dumps(data,indent=2))
